name: Legends_Of_Cysendal
version: 1.0
author: ChenChai
main: ai.chench.legendsofcysendal.Main

commands:
  addsp:
    description: adds soul points to an online player
    usage: /addsp <player> <number of soulpoints>
  getsp:
    description: gets the number of soul points an online player has
    usage: /getsp <player>
